version: 2.1

jobs:
  build:
    docker:
    working_directory: ~/app
    environment:
    steps:
      - checkout

      - run: docker --version
      - run: docker build -t simple-node . 
      - run: docker tag simple-node $DOCKER_USERNAME/simple-node

      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push $DOCKER_USERNAME/simple-node